### ISSUE TITLE
Support for Antminer B3

### ISSUE THREAD

**Issue by brmcc** [anselal/antminer-monitor#100]
Is it possible to add the B3?

I've attached API output..

This one is kind of different.  There are only 3 physical boards, but it shows 6 chains, each with 2 chips.  It also shows 6 temperatures for those chains.  I imagine this will be addressed in another firmware, but the webpage the miner shows the fans always at "0" but they are spinning.  The API shows 30600 so I'm not really sure what to say about that!  I assume the divisor just isn't in place.  Maybe 6 would work, that would be 5100 RPM which feels about like what they are running at.  But I can't really verify this for sure, just taking a guess. 

<script src="https://gist.github.com/brmcc/7504413337218d317c497f81f28860bf.js"></script>

**Comment by brmcc** [comment]
Added support temporarily for myself except for of course fans showing correctly, but this is due to the miner itself.

create_db.py:
models.append(MinerModel(model='B3', chips='2,2,2,2,2,2', temp_keys='temp2_', description='Tensority Miner 780 H/s'))

app/views/antminer.py:
add B3 to total_hash_rate_per_model = 

app/templates/myminers.html:
add  'B3': 'H/s' to mapping

Once Bitmain fixes fan reporting it will work perfect.

**Comment by anselal** [comment]
I think you got the chip count wrong at `models.append...`. It should be `...,chips='4,4,4',...` since the miner has 3 boards and a total of 12 chips...

**Comment by anselal** [comment]
Your gist is unreadable. Can you paste it in json format ?
Also did bitmain fix the issue with the boards showing as 6 instead of 3 ?

**Comment by anselal** [comment]
I think that the number of boards are indeed 3 but the chains are 6. That means that every board has 2 chains...

**Comment by anselal** [comment]
Closed via c0d573d5
