### ISSUE TITLE
Debian rc.local start doesn´t work

### ISSUE THREAD

**Issue by Iseman** [anselal/antminer-monitor#102]
Hi, 

I´m quite new to Linux but wanted to run Antminer Monitor on a Raspberry which works absolutley fine when Ich do start it via the SSH Session. But when I tried to bring it in the start procedure after reboot in the rc.local file it doesn´t start. following Error message is logged in the syslog: 
May 19 15:42:08 raspberrypi rc.local[404]:   File "/home/pi/antmon/manager.py", line 1, in <module>$
May 19 15:42:08 raspberrypi rc.local[404]:   File "/home/pi/antmon/app/__init__.py", line 2, in <module>$

Any ideas what I should Change? 

Iseman

**Comment by jwb6658** [comment]
rc.local runs as sudoers. ensure you install the pip requirements under root.

drop this into rc.local then you can monitor the errors through the log file.

nohup python /home/pi/antminer-monitor/manager.py runserver >> /home/pi/antminer-monitor/errors-startup.log 2>&1 &

**Comment by Iseman** [comment]
> rc.local runs as sudoers. ensure you install the pip requirements under root.

thanks for the hint! After executing the requirements command under sudo it works! Thanks.
