### ISSUE TITLE
Server running at localhost

### ISSUE THREAD

**Issue by papampi** [anselal/antminer-monitor#110]
Last commit server was running at 0.0.0.0:5000
Now its running on 127.0.0.1:5000 and cant be opened from remote locations,
Can you please let us know where to edit to rollback to 0.0.0.0 ?

**Comment by anselal** [comment]
Sorry about that. I forgot to add this to the README

You can set the ip and port at runtime with the following command:

```sh
python manage.py run -h 0.0.0.0 -p 5000
```

I have updated the docs.

Thank you for the feedback @papampi
