### ISSUE TITLE
Add devices by IP address range

### ISSUE THREAD

**Issue by faddat** [anselal/antminer-monitor#111]
Hey, first off, thanks for antminer-monitor!  It's uncomplicated software that does its job well!

Second, we were curious about adding devices by IP address range, for example:

192.168.69.101-200: antminer S9
192.168.70.1-250: antminer L3

Or, is there a way to add these devices in a range using the command line that I just don't know about yet?  

We might be able to add this functionality and submit a PR, if you can point us in the right direction.  Thanks!

**Comment by anselal** [comment]
Thank you for using my software.

Since this is a duplicate, I close it and will comment on #7
