### ISSUE TITLE
Support for E3

### ISSUE THREAD

**Issue by dhellis** [anselal/antminer-monitor#113]
Would love to see both the Bitmain E3 and Z9 added

**Comment by dhellis** [comment]
I will be very happy to provide feedback, Thank you for your consideration

**Comment by dhellis** [comment]
I don't have the full blown Z9, I own the Z9 mini. I don't think the Z9 full version has actuall
shipped to anyone yet

**Comment by anselal** [comment]
So I can add only support for the z9 mini and tbe E3. I will close this issue and open new separate ones.

**Comment by dhellis** [comment]
That works for me and thank you for your time

**Comment by emx0r** [comment]
Hi, I updated the scripts locally to have a support for z9 mini and E3, it works well.
The only problem is that E3 does not return Device Hardware% in STATS query so most likely it'll need a bit of rewrite to fetch it from SUMMARY. I did not have much time to play with it so for now I just set hw errors to 0.

**Comment by louischristy** [comment]
Hi, where can i get the local scripts to support z9 mini?  Also, is there any where i can find a support to monitor Innosilicon T2T?

**Comment by anselal** [comment]
@louischristy There is another issue for z9 mini at #121

**Comment by anselal** [comment]
@louischristy Requests for other miner models are welcome. Please open another issue, one per request.

**Comment by anselal** [comment]
@dhellis Can you post screenshots of the status pages of both miners ?

**Comment by anselal** [comment]
@dhellis Your status page is strange according to bitmain's website.

 - The E3 is supposed to have 3 boards and a total of 18 chips with a hashrate of 190MH/s but your status page shows 9 boards of which a total of 18 chips and a hashrate of 115H/s.
And FYI some boards of yours are fried.

Are you sure that your E3 is working as expected ?

https://shop.bitmain.com/product/detail?pid=00020180831131754682gxyXdS1m0701

In the title you are asking for support for the Z9 but you upload an image of the Z9 mini.
Which is it that you want ?

This issue is getting out of control. Please ask only one thing per issue...

If you want support for the Z9 mini there is another opened issue.

Please clarify.

**Comment by anselal** [comment]
This issue will support only the E3 from now on.

For the Z9 mini see here #121

**Comment by dhellis** [comment]
Thanks for the heads up, this is the first crash I have seen on this machine, a simple
reboot restored it to normal working condition with 203 MH.

**Comment by anselal** [comment]
Can I have some feedback if this is working ok ?

**Comment by anselal** [comment]
I asked because another user stated that there is an error with the E3 in my software.
The E3 takes some time to warm up and load the DAG file. Until then it is not hashing and the miner does not return some of the data causing the app to crash. 

Can you add the E3 and wait some time and then try again to access the app ?
If this works I know how to fix it

**Comment by dhellis** [comment]
No problem, I added the E3, it crashed and will give it some time before trying to run again and
then report back to you

**Comment by dhellis** [comment]
No luck, still crashed


File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2309, in __call__

return self.wsgi_app(environ, start_response)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app

response = self.handle_exception(e)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1741, in handle_exception

reraise(exc_type, exc_value, tb)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise

raise value

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app

response = self.full_dispatch_request()

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request

rv = self.handle_user_exception(e)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise

raise value

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request

rv = self.dispatch_request()

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view

return func(*args, **kwargs)

File "c:\antminer\antminermonitor\blueprints\asicminer\views\antminer.py", line 104, in miners

 [Open an interactive python shell in this frame] worker = active_pool[0]['User']

**Comment by anselal** [comment]
Strange, this should not have been the error. Please try again later...

**Comment by dhellis** [comment]
Yes, it is strange. Running Windows 10 Python 3.7, followed all of the instruction on the main page
including adding the login credentials. Program was installed using Windows administration privleges

**Comment by anselal** [comment]
No, it is a communication and error and the data are not parsed corretly. Will fix it tomorrow and hopefully it will work...

**Comment by dhellis** [comment]
thank you

**Comment by anselal** [comment]
In your previous error the monitor couldn't get the active pool because the E3 hasn't started mining. Obviously it needs more time to warmup.

**Comment by dhellis** [comment]
The E3 has been mining for 6 days since last reboot. But, also the error that I pasted ocassionally
happens with the other miners. After adding the E3 and crashing I did another fresh install and it
would crash while adding the miners back. However it seems to be working okay now (except for the e3)

**Comment by anselal** [comment]
@dhellis I will push some changes and close this issue. Please provide some feedback here if you can after the update

**Comment by dhellis** [comment]
This latest update seems to work just fine. I know it took some time but I am very
happy with the results.

THANK YOU!!
