### ISSUE TITLE
config_lits_of_miners

### ISSUE THREAD

**Issue by Pirojava** [anselal/antminer-monitor#116]
May be instead of registering one-by-one miners in program interface
it would be better to upload config.txt (xml) file with full miners list 
<IP Address>, <Model>, <Remarks>
....
ecc

**Comment by anselal** [comment]
This is possible, but i have a batch add funtion comming

Στις Δευ, 6 Αυγ 2018, 12:18 ο χρήστης Pirojava <notifications@github.com>
έγραψε:

**Comment by anselal** [comment]
This is kinda a duplicate request. See #7
