### ISSUE TITLE
API Allow

### ISSUE THREAD

**Issue by davitosadze** [anselal/antminer-monitor#117]
Hello Anselal, please provide me how can i add API Allow for Miner restart or more (*) marked functions i need this, how can i contact you ?

**Comment by anselal** [comment]
Thank yo for using my software !!!

Adding this functionality is not so easy so I can just tell you. Besides that, there is already another open issue for `restart` and `shutdown`.

This is a duplicate issue. Please check #1

**Comment by davitosadze** [comment]
I'm developer i just need api allow, did you make api allow ? for switchpool or other functions ?

**Comment by anselal** [comment]
There are two ways to do that. The one is via ssh and just reboot the miner and the other is via the cgminer API.
For the second you need the api_allow.
Please check #1 and post your questions there.

**Comment by davitosadze** [comment]
I saw that, but how can i add api_allow code ?

**Comment by anselal** [comment]
Please don't post here anymore..
