### ISSUE TITLE
HW error rate %

### ISSUE THREAD

**Issue by adstek** [anselal/antminer-monitor#136]
The HW error rate does not work on any of my L3+ miners.
and yes, there are some of them that have errors, but it still just says 0.0 or -0.0 on them

**Comment by adstek** [comment]
When I overclock the miners to much, the number of errors starts climbing, but on the monitor it still says 0.0% on some of the miners, and -0.0% on others.
But on my A3, there is a small percentage of errors(0.0835%), but they show up like expected.
Here is a screenshot from on of my L3+'s:
<img width="1135" alt="skjermbilde 2018-11-02 kl 12 55 26" src="https://user-images.githubusercontent.com/35361332/47914512-39c2c700-dea0-11e8-9975-a0da5eab41ab.png">

**Comment by anselal** [comment]
The formula for the HW error rate (%) is:

```sh
HW / (diffA + diffR + HW) * 100
```

This means in your case based on your screenshot you get:

39732 / (4496477635+73264850 + 39732 ) * 100 =>
39732 / 4569782217 * 100 =>
0
