### ISSUE TITLE
Unknown machine support to recognize

### ISSUE THREAD

**Issue by red0bear** [anselal/antminer-monitor#138]
hi there. 

I'm testing your tool and works good .. sometimes give some exception but its ok. but i think could be necessary a feature to add unknown machines  without stay in red cause there is no choice algo yet.

Im looking for support to 

Decred
L3++

**Comment by anselal** [comment]
There is no way to process data from an unknown model.
What exceptions do you sometimes face ? That shouldn't happen

**Comment by red0bear** [comment]
Well ... decred inst listed in your app ..... i put some machines ... in another one .. because i need a list to monitoring..... so i need some custom way to add machines then ?

**Comment by anselal** [comment]
If you want to add a specific miner model just open a new issue for each specific model and if  i need more info I will tell you.
