### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by anselal** [anselal/antminer-monitor#14]
It would be nice to have an auto-refresh feature, maybe even a counter like in the screenshot below.

![antminer-monitor_auto-refresh-feature](https://user-images.githubusercontent.com/8732668/32161447-3c637df6-bd5e-11e7-9c54-0cda443a51c2.png)

**Comment by babycicak** [comment]
I love this idea!

**Comment by anselal** [comment]
I set the time interval to 120 seconds

**Comment by babycicak** [comment]
if you can auto restart those miner where chips XXXX  will be even more better :D

**Comment by anselal** [comment]
@babycicak open a new issue about that and I will comment there ;)
