### ISSUE TITLE
No such command "create_db".

### ISSUE THREAD

**Issue by gaia** [anselal/antminer-monitor#143]
```
$ python --version
Python 2.7.15rc1

$ python manage.py create_db
Usage: manage.py [OPTIONS] COMMAND [ARGS]...
Try "manage.py --help" for help.

Error: No such command "create_db".

```

running the app works, and I can login (didn't run create_admin either, same error as above), but it obviously gets to a "table not found" error.

**Comment by anselal** [comment]
Be sure to have the latest version of AntminerMonitor installed.

If you type`python manage.py` you should get a list with all available options. Can you check ?

**Comment by gaia** [comment]
I do get the list of options.

**Comment by anselal** [comment]
Maybe a typo ?

**Comment by gaia** [comment]
tried many times, copy and paste included. I am on Windows Linux Subsystem (?)

**Comment by anselal** [comment]
You just mentioned that you are on WSL. Should be the first think you should have told.

Maybe it is a WSL related issue. It runs fine on Linux, Unix, Mac and Windows systems.

**Comment by gaia** [comment]
same error on windows: https://i.imgur.com/GlmwX6H.png

i also tried it on mac, same error, but i have no screenshot (it was done before I tried it on WSL)

**Comment by anselal** [comment]
According to your screenshot all the commands has been changed for some reason from an underscore (`_`) to a dash `-` so you have to run the following commands accordingly:

```sh
python manage.py create-db
```

```sh
python manage.py update-db
```

```sh
python manage.py create-admin
```

**Comment by gaia** [comment]
the underscore comes from your instructions: https://i.imgur.com/u6JnhpM.png
thank you for your help!

**Comment by anselal** [comment]
Correct. It should be an underscore since it is defined so. Don't know why this is happening to you.

I am glad I helped. Donations are always welcome !!!
