### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dhellis** [anselal/antminer-monitor#146]
I found a bug where if a machine (in my case an Antminer D3) was up but hash rate 
was 0 (zero) the program would crash.

When looking at my web screen, I noticed the crash, tried to restart but no luck
so I deleted the db, created a new db then added machines again from scratch.
When I got to the D3 with the problem, the program crashed immediately.
Since the OS was running on that D3 I logged in, noticed the 0 hash rate and rebooted
the machine.

I also had a copy of the db that I had been using so copied backup.db to app.db
restarted the program and everything was restored.

**Comment by anselal** [comment]
I close this issue due to inactivity. Feel free to reopen
