### ISSUE TITLE
Auto Restart

### ISSUE THREAD

**Issue by babycicak** [anselal/antminer-monitor#15]
i hope it will be auto restart function on this software, once the page is refresh and if any running chip XXXXX it will be auto restart for them.

**Comment by anselal** [comment]
Auto-features like this should be added only when the admin interface is ready. The user shall have to option to turn such functionality `on & off`.
I am concerned about the reason you wanna auto-restart the miner. The `Xs` usually mean a broken ASIC chip. Every `X` represents a broken/burned chip. Rebooting the miner will not fix this issue. Do you agree ??

**Comment by babycicak** [comment]
No. XXX is failure of PSU or sometime not enough 12V+, Restart the miner will help. My current D3s having this issue.

If chip is broken, it will display ----- or not display anything. 

I think im correct.

**Comment by anselal** [comment]
@babycicak Check this out https://bitmainhelp.zendesk.com/hc/en-us/articles/220872007-Possible-problems-for-Antminer-Troubleshooting-for-S7-S9
According to issues  3&4 the `X` means damaged chip.
According to issue 5 a lot of `-` mean instability of the power supply voltage or defective hash board.
I will add `-` to the table though.

**Comment by babycicak** [comment]
Yes, i read that too just now. But, i speak from my experience.
Maybe manual restart is better in this case.  :D

**Comment by anselal** [comment]
@babycicak I opened a new issue to add the info about the dashes `-` to the table. Maybe manually rebooting the miner is a better solution, although I can add a notification about that part. For the moment I close this issue. 

Thank yo u for the feedback !!
