### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by Omgthehorror** [anselal/antminer-monitor#150]
I'm getting an error after I try and login with the default user admin/antminermonitor
`sqlalchemy.exc.OperationalError
OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.surname AS user_surname, user.firstname AS user_firstname, user.active AS user_active 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: (u'admin', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)`

**Comment by anselal** [comment]
Please read the readme.

You have to create the tables first.

https://github.com/anselal/antminer-monitor/blob/master/README.md#login-page

**Comment by Omgthehorror** [comment]
I have used `python manage.py create-db` to create the DB and if I try again it returns [INFO] Database already exists.

By the way in the latest version commands for manage.py are with a dash instead of underscore as stated in the readme.

**Comment by anselal** [comment]
My friend, again, read the readme.

Follow the link i just sent you. You have to create the admin account.
