### ISSUE TITLE
Add chip status '-' to the table

### ISSUE THREAD

**Issue by anselal** [anselal/antminer-monitor#16]
Besides `X` and `o` as the chip's status there is also the dash `-` which means instability of the power supply voltage or the defective hash board

Source: https://bitmainhelp.zendesk.com/hc/en-us/articles/220872007-Possible-problems-for-Antminer-Troubleshooting-for-S7-S9 , issue 5

Rebooting the miner may sometimes fix this issue although it is not a permanent solution !!!

**Comment by babycicak** [comment]
Reboot is helping when you're travel away/ or cant access the farm immediately. Maybe just trace the total working chips as the software did is the best solution. + add the Manual Reboot button.
