### ISSUE TITLE
max worker must be greater than 0

### ISSUE THREAD

**Issue by jcreyesb** [anselal/antminer-monitor#175]
![Captura de pantalla de 2020-08-28 08-46-59](https://user-images.githubusercontent.com/25069358/91562376-1c7baa00-e90b-11ea-8768-ad4836ff05ab.png)

**Comment by old06** [comment]
+

**Comment by old06** [comment]
> ![Captura de pantalla de 2020-08-28 08-46-59](https://user-images.githubusercontent.com/25069358/91562376-1c7baa00-e90b-11ea-8768-ad4836ff05ab.png)

edit settings.py 
import multiprocessing as m
NUM_THREADS=m.cpu_count()-1

import multiprocessing as m
NUM_THREADS=m.cpu_count()
 its work

**Comment by anselal** [comment]
@old06  do you run it in a single core cpu ?

**Comment by old06** [comment]
@anselal  yes

**Comment by anselal** [comment]
ok, will fix that later today.
thnx for the feedback
