### ISSUE TITLE
Support for Antminer S11

### ISSUE THREAD

**Issue by writzoner** [anselal/antminer-monitor#176]
Hey, I've been using your AMM since 0.03 (i think the version was.). I had noticed that this hasn't been updated in a while and if you're still maintaining this could you add info for the Antminer S11?

I appreciate all the work you've done over the years!

**Comment by anselal** [comment]
Hi there, thank you for using my software.
Will add the miner tomorrow.

As always, donations are welcome !!!

**Comment by anselal** [comment]
@writzoner this should do the work

**Comment by writzoner** [comment]
Thanks! Works a treat.
Quick question about the miner discovery, what format is the subnet in? It keeps telling me to match the requested format, and I’ve tried all the ones I’m using?

Sent from Mail for Windows 10

**Comment by anselal** [comment]
Sorry for that, I thought I had added a placehkder for that field. Since it concatenates the start/end ip with submet the subnet must be in the following form: `192.168.1` so you must enter only the 24 first bits

**Comment by writzoner** [comment]
See, I had tried that, and I get the same response.


Sent from Mail for Windows 10

**Comment by anselal** [comment]
What subnet are you entering? I wanna check if it oasses the regular expression. Also, it would be better to move the conversasion over to a new issue, please open one.

**Comment by anselal** [comment]
Please open a new issue if no other one exists, open or closed. Thnx

**Comment by anselal** [comment]
@writzoner Did you send me the last donation?

**Comment by writzoner** [comment]
Yes!

Sent from Mail for Windows 10

**Comment by anselal** [comment]
thank you very much for that, I  really appreciate it

**Comment by writzoner** [comment]
Anytime, you did me a huge solid! That’s the least I could do. 

Sent from Mail for Windows 10
