### ISSUE TITLE
Miner discovery subnet?

### ISSUE THREAD

**Issue by voljumet** [anselal/antminer-monitor#179]
Hi, I'm trying to use the miner discovery, but no matter what I use as subnet It just gives me the error "Please match the requested format: Please add a valid network subnet".
In the other two boxes, it at least gives a hint on what to write in the boxes. found another issue with the same question, but no answer on it.

**Comment by anselal** [comment]
Hi, i think the format was 192.168.1 but let me check.
What was it you were trying to input?

**Comment by anselal** [comment]
@voljumet the format is the one i mentioned above. I should add a placeholder for that field, you are right.

eg. 
Subnet: 192.168.1
Start: 1
End: 254

Let me know if that worked

**Comment by voljumet** [comment]
aha, i wrote "10.2.204.0" 
maybe add a tooltip to the box?

**Comment by anselal** [comment]
@voljumet so did it work ?

**Comment by anselal** [comment]
@voljumet did it work ?
