### ISSUE TITLE
Support for Antminer s17+

### ISSUE THREAD

**Issue by dkhan99** [anselal/antminer-monitor#180]
Can you add support for Antminer s17+ (plus)

**Comment by anselal** [comment]
Hi, yes will try to find data for it

**Comment by anselal** [comment]
Ok, i found data. Will add it later today in a couple of hours probably

**Comment by dkhan99** [comment]
Awesome, thank you so much. Let me know if you need anything from my end

**Comment by anselal** [comment]
> Awesome, thank you so much. Let me know if you need anything from my end

should be ready now. let me know if everything works as expected
