### ISSUE TITLE
Antminer S9i

### ISSUE THREAD

**Issue by old06** [anselal/antminer-monitor#181]
Please add Antminer S9i.

**Comment by anselal** [comment]
@old06 thnx for using my software.
are there any significant differences between S9 and s9i ?

**Comment by old06** [comment]
i am edit model.json
    "Antminer S9": {
        "id": "Antminer S9",
        "model": "S9",
        "chips": "63,63,63",
        "temp_keys": "temp2_",
        "unit": "GH/s",
        "description": "Bitmain Antminer S9 Bitcoin Miner 13.5 TH/s",
        "model_module": "antminermonitor.blueprints.asicminer.asic_antminer",
        "model_classname": "ASIC_ANTMINER"
    },
    "Antminer S9i": {
        "id": "Antminer S9i",
        "model": "S9i",
        "chips": "63,63,63",
        "temp_keys": "temp2_",
        "unit": "GH/s",
        "description": "Bitmain Antminer S9i Bitcoin Miner 13.5 TH/s",
        "model_module": "antminermonitor.blueprints.asicminer.asic_antminer",
        "model_classname": "ASIC_ANTMINER"
    },
Work. right ?

**Comment by anselal** [comment]
it should. since you changed only the name there is no actual need to add it, but ok..
if it works for you please close the issue

**Comment by old06** [comment]
Thaks
