### ISSUE TITLE
new page mobile

### ISSUE THREAD

**Issue by HMCmin** [anselal/antminer-monitor#183]
It is possible to edit home.html to new page like mobile.html witch show only total hashrate and inactive and active miners count ?

Best Regards

**Comment by anselal** [comment]
You can edit the html files and remove the cells you don't want to be displayed

**Comment by HMCmin** [comment]
> You can edit the html files and remove the cells you don't want to be displayed

ok, but how create new route ?

Best Regards

**Comment by anselal** [comment]
Sorry, but I cannot guide you trough the whole process.
My app is based on python flask. you can read their documentation if you want
