### ISSUE TITLE
Not work at Python 2.7.17 on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by iacsvrn** [anselal/antminer-monitor#188]
Downloading https://files.pythonhosted.org/packages/d9/1f/27dff5c1ea8f36865a179581dea4f75d1ab52cd8f32ee527a592b6558b55/validators-0.17.0.tar.gz
validators requires Python '>=3.4' but the running Python is 2.7.17

**Comment by anselal** [comment]
> Downloading https://files.pythonhosted.org/packages/d9/1f/27dff5c1ea8f36865a179581dea4f75d1ab52cd8f32ee527a592b6558b55/validators-0.17.0.tar.gz validators requires Python '>=3.4' but the running Python is 2.7.17

Python 2 is not supported anymore

**Comment by iacsvrn** [comment]
Thnks, update plz this info:

"Antminer Monitor requires Python to run. Both Python2 and Python3 are supported !!!"

**Comment by anselal** [comment]
Sorry about this, you are right.
Thought I did update it
