### ISSUE TITLE
python manage.py create-db not work

### ISSUE THREAD

**Issue by iacsvrn** [anselal/antminer-monitor#189]
Python 3.8.2
Ubuntu 20.04 LTS

====

Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from antminermonitor.app import create_app
  File "/home/antminer-monitor/antminer-monitor/antminermonitor/app.py", line 4, in <module>
    from antminermonitor.blueprints.user import user
  File "/home/antminer-monitor/antminer-monitor/antminermonitor/blueprints/user/__init__.py", line 1, in <module>
    from antminermonitor.blueprints.user.views import user
  File "/home/antminer-monitor/antminer-monitor/antminermonitor/blueprints/user/views.py", line 6, in <module>
    from antminermonitor.blueprints.user.forms import LoginForm, PasswordResetForm
  File "/home/antminer-monitor/antminer-monitor/antminermonitor/blueprints/user/forms.py", line 2, in <module>
    from wtforms.fields import BooleanField, PasswordField, SelectField, TextField
ImportError: cannot import name 'TextField' from 'wtforms.fields' (/usr/local/lib/python3.8/dist-packages/wtforms/fields/__init__.py)

====

All requirement already satisfied:

Requirement already satisfied: Flask==1.1.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: Flask-Login==0.5.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (0.5.0)
Requirement already satisfied: Flask-Migrate==2.5.2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (2.5.2)
Requirement already satisfied: Flask-WTF==0.14.3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (0.14.3)
Requirement already satisfied: python-dotenv==0.11.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (0.11.0)
Requirement already satisfied: SQLAlchemy==1.3.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: WTForms-Components==0.10.4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (0.10.4)
Requirement already satisfied: gunicorn in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 11)) (20.1.0)
Requirement already satisfied: isort==4.3.21 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 14)) (4.3.21)
Requirement already satisfied: yapf==0.29.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 15)) (0.29.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.8/dist-packages (from Flask==1.1.1->-r requirements.txt (line 2)) (8.0.3)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.8/dist-packages (from Flask==1.1.1->-r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.8/dist-packages (from Flask==1.1.1->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.8/dist-packages (from Flask==1.1.1->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: alembic>=0.7 in /usr/local/lib/python3.8/dist-packages (from Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (1.7.5)
Requirement already satisfied: Flask-SQLAlchemy>=1.0 in /usr/local/lib/python3.8/dist-packages (from Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (2.5.1)
Requirement already satisfied: WTForms in /usr/local/lib/python3.8/dist-packages (from Flask-WTF==0.14.3->-r requirements.txt (line 5)) (3.0.0)
Requirement already satisfied: validators>=0.5.0 in /usr/local/lib/python3.8/dist-packages (from WTForms-Components==0.10.4->-r requirements.txt (line 8)) (0.18.2)
Requirement already satisfied: intervals>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from WTForms-Components==0.10.4->-r requirements.txt (line 8)) (0.9.2)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from WTForms-Components==0.10.4->-r requirements.txt (line 8)) (1.14.0)
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn->-r requirements.txt (line 11)) (45.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=2.10.1->Flask==1.1.1->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: importlib-resources; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from alembic>=0.7->Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (5.4.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.8/dist-packages (from alembic>=0.7->Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (1.1.6)
Requirement already satisfied: importlib-metadata; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from alembic>=0.7->Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (4.10.0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from validators>=0.5.0->WTForms-Components==0.10.4->-r requirements.txt (line 8)) (5.1.0)
Requirement already satisfied: infinity>=0.1.3 in /usr/local/lib/python3.8/dist-packages (from intervals>=0.6.0->WTForms-Components==0.10.4->-r requirements.txt (line 8)) (1.5)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from importlib-resources; python_version < "3.9"->alembic>=0.7->Flask-Migrate==2.5.2->-r requirements.txt (line 4)) (3.6.0)

**Comment by anselal** [comment]
I am in the process of fixing this.
Please do `pip install WTForms == 2.3.3`

**Comment by iacsvrn** [comment]
pip3 install WTForms==2.3.3 is ok work. add plz, that peolple must run pip3, not pip

**Comment by iacsvrn** [comment]
> I am in the process of fixing this. Please do `pip install WTForms == 2.3.3`

Not work...

===

python manage.py create-db
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from antminermonitor.app import create_app
ModuleNotFoundError: No module named 'antminermonitor'

===

**Comment by anselal** [comment]
Did you maybe delete some files ?
I just tested it and there is no error. Also please use a version between 3.5 and 3.8 as I didn't test it on the latest versions

**Comment by iacsvrn** [comment]
All is ok at PYthon 3.7. DB has been created.

**Comment by iacsvrn** [comment]
I`ll recommend add to description and required packages. this will simplify installation this:

apt install python-is-python3
