### ISSUE TITLE
Board Temperature Order 

### ISSUE THREAD

**Issue by l2airj** [anselal/antminer-monitor#2]
I notice that the board temperature is not in the same order as it is on the miner that will be great if it can be fix so We can know which board exactly is heating up

**Comment by anselal** [comment]
@l2airj I have noticed that too. I thought that it wouldn't mind the user. It was not so easy to implement but since you are asking for, I will do my best to not let you down. We have the same issues with the fan speeds, the hash speed (feature release).

**Comment by anselal** [comment]
Fixed. Please check and if any errors you can reopen this issue
