### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by writzoner** [anselal/antminer-monitor#20]
This is occurring during the pip install -r requirements.txt initialization.

 $ wget https://github.com/anselal/antminer-monitor.git
--2017-11-04 01:59:12--  https://github.com/anselal/antminer-monitor.git
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/anselal/antminer-monitor [following]
--2017-11-04 01:59:13--  https://github.com/anselal/antminer-monitor
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘antminer-monitor.git’

antminer-monitor.git               [ <=>                                                   ]  59.26K  --.-KB/s   in 0.09s

2017-11-04 01:59:13 (673 KB/s) - ‘antminer-monitor.git’ saved [60682]

 $ ls
antminer-monitor.git  dns_update_script.sh  html
 $ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by anselal** [comment]
Hi there,

you are doion it all wrong. You don't wget the .git file. 
Either `git clone https://github.com/anselal/antminer-monitor.git` 
or 
`wget https://github.com/anselal/antminer-monitor/archive/master.zip`

**Comment by writzoner** [comment]
awesome, thanks! it worked like a charm!
(running it on a rPI)
