### ISSUE TITLE
Miners not being detected as active?

### ISSUE THREAD

**Issue by nullwriter** [anselal/antminer-monitor#24]
Heya, I tried adding my S9's but they are shown as inactive with Error: Check connection or IP Address?

Also, for the T9s should we add them as S9?

When i run pycgminer.py with the ip of one of the miners, I do get a response from it:

`{u'STATUS': [{u'STATUS': u'S', u'Msg': u'BMMiner stats', u'Code': 70, u'When': 1503889968, u'Description': u'bmminer 1.0.0'}], u'STATS': [{u'Type': u'Antminer S9', u'CompileTime': u'Wed Jun 8 18:26:47 CST 2016', u'Miner': u'4.0.1.0', u'BMMiner': u'1.0.0'}, {u'GHS 5s': 11398.58, u'temp_max': 62, u'Elapsed': 54370, u'temp2_10': 0, u'temp2_11': 0, u'temp2_12': 0, u'temp2_13': 0, u'temp2_14': 0, u'temp2_15': 0, u'temp2_16': 0, u'Wait': 0.0, u'Device Hardware%': 0.0002, u'chain_acs11': u'', u'chain_acs10': u'', u'chain_acs13': u'', u'chain_acs12': u'', u'chain_acs15': u'', u'chain_acs14': u'', u'chain_acs16': u'', u'temp_num': 3, u'temp3': 62, u'temp2': 0, u'temp1': 62, u'frequency': u'550', u'temp7': 0, u'temp6': 0, u'temp5': 0, u'temp4': 61, u'temp9': 0, u'temp8': 0, u'Calls': 0, u'chain_hw2': 0, u'chain_hw3': 172, u'chain_hw1': 96, u'chain_hw6': 0, u'chain_hw7': 0, u'chain_hw4': 95, u'chain_hw5': 0, u'chain_hw8': 0, u'chain_hw9': 0, u'fan1': 4320, u'fan3': 0, u'fan2': 6360, u'chain_acs9': u'', u'chain_acs8': u'', u'fan7': 0, u'fan6': 0, u'chain_acs5': u'', u'chain_acs4': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo', u'chain_acs7': u'', u'chain_acs6': u'', u'chain_acs1': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo', u'chain_rate12': u'', u'chain_acs3': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo', u'chain_acs2': u'', u'chain_hw14': 0, u'chain_hw15': 0, u'chain_hw16': 0, u'chain_hw10': 0, u'chain_hw11': 0, u'chain_hw12': 0, u'chain_hw13': 0, u'fan_num': 2, u'chain_rate16': u'', u'chain_acn10': 0, u'chain_acn11': 0, u'chain_acn12': 0, u'chain_acn13': 0, u'chain_acn14': 0, u'chain_acn15': 0, u'chain_acn16': 0, u'STATS': 0, u'temp2_8': 0, u'temp2_9': 0, u'temp2_6': 0, u'temp2_7': 0, u'temp2_4': 91, u'temp2_5': 0, u'temp2_2': 0, u'temp2_3': 95, u'temp2_1': 92, u'chain_rate15': u'', u'chain_rate9': u'', u'chain_rate8': u'', u'Min': 99999999.0, u'chain_rate3': u'3886.39', u'chain_rate2': u'', u'chain_rate1': u'3974.74', u'chain_rate7': u'', u'chain_rate6': u'', u'chain_rate5': u'', u'chain_rate4': u'3908.29', u'miner_count': 3, u'GHS av': 11802.58, u'chain_acn8': 0, u'chain_acn9': 0, u'chain_acn2': 0, u'Max': 0.0, u'chain_acn1': 63, u'chain_acn6': 0, u'chain_acn7': 0, u'chain_acn4': 63, u'chain_acn5': 0, u'temp13': 0, u'temp12': 0, u'temp11': 0, u'temp10': 0, u'temp16': 0, u'temp15': 0, u'temp14': 0, u'fan5': 0, u'fan4': 0, u'no_matching_work': 363, u'fan8': 0, u'ID': u'BC50', u'chain_rate14': u'', u'chain_rate13': u'', u'chain_rate11': u'', u'chain_acn3': 63, u'chain_rate10': u''}], u'id': 1}`

**Comment by anselal** [comment]
Are you sure you enter the IP address correctly ? Just add the IP without any port number and be sure to remove and whitespaces. This is strange though since you get an output from the command line. If the above doesn't fix your issue you can send me an email and we can connect with TeamViewer so I get a look at your setup.
To add support for the T9 I'll need some info. Can you open a new issue with title `Antminer T9 support` and paste the output of the pycgminer script (stats command) ?

**Comment by anselal** [comment]
I found the info I need to add support for the T9. If you add the T9 as S9 you will get some errors since the T9 has fewer chips than the S9, so the warning will indicate that some chips are missing.

I will add support for the T9 probably in the next release

**Comment by nullwriter** [comment]
@anselal Here's a screenshot. I want to note I'm running this in python 3, not sure if its what's expected to run well, as you state python 2 to run it.

<img width="1116" alt="screen shot 2017-11-10 at 11 40 45 am" src="https://user-images.githubusercontent.com/3685440/32666506-19db1ef4-c5e4-11e7-8196-670eb000607a.png">

**Comment by anselal** [comment]
At the moment the app only supports Python2. Pycgminer when run in Python3.6 throws an error (#10). 
I find it strange that you got an output. Which python version are you using? Can you try with Python2 and let me know if it works for you?

**Comment by nullwriter** [comment]
I just realised I ran pycgminer with python 2. With python 3 it does throw the error as you said.

**Comment by anselal** [comment]
Have you tried running the app with Python2 ? If it works we can close this issue

**Comment by anselal** [comment]
@nullwriter can you let us know if everything worked out so I can close this issue?

**Comment by anselal** [comment]
This issue is resolved thus I close it
