### ISSUE TITLE
Antminer T9 support

### ISSUE THREAD

**Issue by nullwriter** [anselal/antminer-monitor#25]
Heres the output for pycgminer.py of my T9:

`{u'STATUS': [{u'STATUS': u'S', u'Msg': u'BMMiner stats', u'Code': 70, u'When': 127916, u'Description': u'bmminer 1.0.0'}], u'STATS': [{u'Type': u'Antminer T9', u'CompileTime': u'Tue Feb 28 22:00:37 EST 2017', u'Miner': u'13.8.1.3', u'BMMiner': u'2.0.0'}, {u'miner_version': u'13.8.1.3', u'chain_hw11': 0, u'GHS 5s': u'12714.95', u'chain_xtime8': u'{}', u'temp_max': 84, u'Elapsed': 127743, u'temp2_10': 0, u'temp2_11': 0, u'temp2_12': 0, u'temp2_13': 0, u'temp2_14': 0, u'temp2_15': 0, u'temp2_16': 0, u'chain_acs4': u'', u'Wait': 0.0, u'Device Hardware%': 0.0, u'chain_acs11': u'', u'chain_acs10': u'', u'chain_acs13': u'', u'chain_acs12': u'', u'chain_acs15': u'', u'chain_acn9': 0, u'chain_acs16': u'', u'chain_rateideal15': 0.0, u'chain_rateideal14': 0.0, u'chain_rateideal16': 0.0, u'chain_rateideal11': 0.0, u'chain_rateideal10': 0.0, u'chain_rateideal13': 0.0, u'chain_rateideal12': 0.0, u'chain_rate4': u'', u'freq_avg1': 0.0, u'freq_avg2': 0.0, u'freq_avg3': 0.0, u'freq_avg4': 0.0, u'freq_avg5': 0.0, u'freq_avg6': 641.21, u'freq_avg7': 641.31, u'freq_avg8': 641.94, u'freq_avg9': 0.0, u'temp_num': 3, u'temp3': 0, u'temp2': 0, u'temp1': 0, u'frequency': u'656', u'temp7': 68, u'temp6': 70, u'temp5': 0, u'temp4': 0, u'temp9': 0, u'temp8': 73, u'chain_offside_7': u'0', u'Calls': 0, u'chain_hw2': 0, u'chain_rateideal5': 0.0, u'chain_hw1': 0, u'chain_hw6': 16, u'chain_hw7': 16, u'chain_hw4': 0, u'chain_rateideal4': 0.0, u'chain_hw8': 20, u'chain_hw9': 0, u'chain_rateideal7': 4167.27, u'fan1': 0, u'fan3': 5280, u'fan2': 0, u'fan5': 0, u'fan4': 0, u'fan7': 0, u'fan6': 4440, u'chain_acs5': u'', u'fan8': 0, u'chain_acs7': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo o', u'chain_acs6': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo o', u'chain_acs1': u'', u'chain_rate12': u'', u'chain_acs3': u'', u'chain_acs2': u'', u'chain_hw14': 0, u'chain_hw15': 0, u'chain_hw16': 0, u'chain_hw10': 0, u'chain_rateideal3': 0.0, u'chain_hw12': 0, u'chain_hw13': 0, u'fan_num': 2, u'chain_rate16': u'', u'chain_acn10': 0, u'chain_acn11': 0, u'chain_acn12': 0, u'chain_acn13': 0, u'chain_acn14': 0, u'chain_acn15': 0, u'chain_acn16': 0, u'chain_rateideal8': 4167.51, u'total_freqavg': 641.49, u'chain_xtime7': u'{}', u'chain_rate2': u'', u'chain_rate1': u'', u'STATS': 0, u'chain_hw3': 0, u'chain_acs14': u'', u'chain_rate6': u'4239.52', u'chain_acn8': 57, u'temp2_8': 69, u'temp2_9': 0, u'temp2_6': 72, u'temp2_7': 78, u'temp2_4': 0, u'temp2_5': 0, u'temp2_2': 0, u'temp2_3': 0, u'temp2_1': 0, u'chain_hw5': 0, u'chain_rate15': u'', u'chain_rate9': u'', u'chain_rate8': u'4242.09', u'Min': 99999999.0, u'temp3_13': 0, u'temp3_12': 0, u'temp3_11': 0, u'temp3_10': 0, u'chain_rate7': u'4233.34', u'temp3_16': 0, u'temp3_15': 0, u'temp3_14': 0, u'chain_rate3': u'', u'miner_count': 3, u'total_acn': 171, u'GHS av': 12726.94, u'freq_avg12': 0.0, u'freq_avg13': 0.0, u'freq_avg10': 0.0, u'freq_avg11': 0.0, u'freq_avg16': 0.0, u'freq_avg14': 0.0, u'freq_avg15': 0.0, u'chain_acn2': 0, u'Max': 0.0, u'chain_acn1': 0, u'chain_acn6': 57, u'chain_acn7': 57, u'chain_acn4': 0, u'chain_acn5': 0, u'temp13': 0, u'temp12': 0, u'temp11': 0, u'temp10': 0, u'temp16': 0, u'temp15': 0, u'temp14': 0, u'chain_acs9': u'', u'chain_acs8': u' oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo o', u'total_rate': 12714.95, u'chain_rateideal6': 4166.58, u'no_matching_work': 53, u'temp3_7': 82, u'temp3_6': 82, u'temp3_5': 0, u'temp3_4': 0, u'temp3_3': 0, u'temp3_2': 0, u'temp3_1': 0, u'chain_rateideal2': 0.0, u'chain_rateideal9': 0.0, u'ID': u'BC50', u'temp3_9': 0, u'temp3_8': 84, u'chain_rate5': u'', u'chain_rate14': u'', u'chain_rate13': u'', u'chain_rateideal1': 0.0, u'chain_xtime6': u'{}', u'chain_opencore_6': u'1', u'chain_opencore_7': u'1', u'chain_rate11': u'', u'chain_offside_8': u'0', u'chain_acn3': 0, u'chain_offside_6': u'0', u'total_rateideal': 12501.37, u'chain_rate10': u'', u'chain_opencore_8': u'1'}], u'id': 1}`

**Comment by rw86347** [comment]
I am an iPhone programmer and I have a T9.  If the developer wants to point me in the right direction I will add it.

**Comment by anselal** [comment]
Hello @rw86347, thank you for using my app. To add support for the T9 we'll have to update the database. The reason I haven't done it yet is because lack of time and because I want to create an update script so that a user who comes from a previous version won't have to delete the database and add the miners from the start.

Please be patient as a new release with come after Xmas. For now you can add your T9 as S9 and ignore the errors

**Comment by AndreyNag** [comment]
Hi. I need add support for Pantech X5, SX6, Hotminer X7 etc. Can you tell us how we can add it?

**Comment by anselal** [comment]
@AndreyNag I am not aware of those miners. Can you please open a new issue and post some links so I take a look at them ?

**Comment by gnanet** [comment]
Also if those miners support the same api please include an anonymized version of the output of stats and summary and devs.
