### ISSUE TITLE
Installation problems (noob questions)

### ISSUE THREAD

**Issue by Bitweidi** [anselal/antminer-monitor#27]
Hi there - want to try you awesome tool but im struggling with python for hours :( (no coding skills)
Minera is not working for my L3+s and AwesomeMiner wont run on a Raspberry Pi - so you project would be perfect!

On a Windows machine i installed python 2.7 from the link in your description. In a command promt i downloaded the requirements and created a database. Seemed to be working.

Now i run the command: python run.py and this message appears: 
```
C:\Python27>python run.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 220-713-037
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Whats next? Tried to open this IP in a webbrowser or open the myminers.html file but none of this works. Sorry for my stupid questions - is my first time with python or anything like that.

My second issue - i want to run this script on a Raspberry Pi3. Can you give me some instructions how to get this working? Which OS for the Pi and so on?

Thank you VERY MUCH! (noob guy from twitter)

**Comment by anselal** [comment]
You have compleres the installation. Fire up a browser and point it at localhost:5000 or 127.0.0.1:5000

The 0.0.0.0:5000 means that the app is accesible not only from your local computer but you can access it from any computer in the network and any computer in the worls as long as you give access from your router.

The installation instructions are the same for any OS but in Linux python is already installed as I already mention in the instructions

**Comment by Bitweidi** [comment]
Thank you very much! 
So you think any Pi Operating System should work? Trying Raspbian then. 
Sending some BTC when mempool goes down again ;)

Keep up the great work!

**Comment by anselal** [comment]
Raspbian is a good OS to start. I run raspbian lite on an old rpi model b. It has no gui installed so it is much liter since this old rpi has only 512 MB of ram but the app runs great even on an old hardware like this.

Thank you very much for the support. I really appreciate it !!!

**Comment by anselal** [comment]
@Bitweidi You can get informed about the best tx fee at https://bitcoinfees.earn.com/
