### ISSUE TITLE
Request Full Guide

### ISSUE THREAD

**Issue by kee4834** [anselal/antminer-monitor#30]
Hi,

Any Full guide for this?

Thanks in advanced

**Comment by anselal** [comment]
Hi, there is no guide but the app is pretty simple. Just add the miners using the form in the app and start monitoring. I will add a "how to use" section in the readme file, probably later tonight or tomorrow, since you requested it. You are welcome to try the app and leave some feedback.

**Comment by gnanet** [comment]
i tend to create a bunch of screenshots and a bit for-the-user like instructons about how your app can be used, ill report when im done or better ill create a fork+PR then

**Comment by anselal** [comment]
@gnanet You do that and we'll see how it goes...

**Comment by mikespax** [comment]
Windows:

Download and install Python. Download and unzip Antminer-Monitor. 
 
Right click on command prompt to run as administrator. With the Python install in the default folder, and Antminer-Monitor renamed and placed into c:\monitor the follow lines should work.
First you need to cd into the location of the github directory that you've unzipped. I've renamed the folder and placed it into c:\monitor to save a few keystrokes.

cd c:\monitor
c:\python27\python.exe -m pip install -r requirements.txt
c:\python27\python.exe create_db.py
c:\python27\python.exe run.py

Then just visit localhost:5000 and you're done!

OSX

Open your terminal.
Install PIP using this command: sudo easy_install pip
Type in your password and press enter to begin the installation.

Download and unzip the Antminer-Monitor

In terminal, point to the directory you've just unzipped using the cd command, then just follow the following sudo commands.

cd /Applications/antminer-monitor-master
sudo python -m pip install -r requirements.txt
sudo python create_db.py
sudo python run.py

Crack open localhost:5000 and you're done!

**Comment by anselal** [comment]
Nice job @mikespax, I didn;t know that `easy_install` was part of OSX.

**Comment by gnanet** [comment]
Install docs seem to get quickly in shape, so i should give me a boost, to get that "for the user" screenshot thing done too... :(

**Comment by kee4834** [comment]
Thx for the guide, does it support raspberry pie also?

**Comment by kee4834** [comment]
Hi Guys,

I'm facing issue with another PC,How do I solve this?

c:\python27\python.exe: can't open file 'run.py': [Errno 2] No such file or directory

Thanks in advanced

**Comment by anselal** [comment]
@kee4834 If you have update to latest version you should read the documentation (README.md file) on how to start the app since some things have changed.

**Comment by kee4834** [comment]
Hi,

Any guide setup for debian?

Thx in advance

**Comment by errand** [comment]
For Debian I can give you a contact of system administrator ;)

**Comment by kee4834** [comment]
OK TQ

**Comment by errand** [comment]
@kee4834 , boris.syomov[amp]gmail.com His name is Boris, really nice guy.

**Comment by anselal** [comment]
@kee4834 
The installation instructions are for debian too !!!

**Comment by anselal** [comment]
Just follow the README

**Comment by anselal** [comment]
I close this issue due to inactivity. Feel free to reopen
