### ISSUE TITLE
Reboot when detected chips (Os) =/= 180

### ISSUE THREAD

**Issue by ckl33** [anselal/antminer-monitor#31]
I have a couple of weird D3s that sometimes say 175-179 chips are Os and the rest are Xs and are fixed with a simple reboot on their static ip page, it'd be great to have a built in option to automatically reboot the miner if any Xs are detected.

**Comment by anselal** [comment]
Bitmain has released a firmware update for the D3 at https://shop.bitmain.com/support.htm?pid=00720170915192851224mJ36J1ap066E which resolves your problem Besides that the reboot feature is requested in #1

**Comment by ckl33** [comment]
Nah, all my firmware has been upgraded, the D3s are a buggy release.

**Comment by anselal** [comment]
Check #21 for a conversation about the auto-reboot feature
