### ISSUE TITLE
Low socket timeout causing KeyError: 'POOLS' & dark theme

### ISSUE THREAD

**Issue by MartinPajak** [anselal/antminer-monitor#33]
I'm running it on windows 10 for 4xD3 and got an exception on
`worker = miner_pools['POOLS'][0]['User']` 
in antminer.py with index "POOLS", so changed it for testing to 
`           try:
                worker = miner_pools['POOLS'][0]['User']
            except Exception as e:
                miner_pools = get_pools(miner.ip)
                worker = miner_pools['POOLS'][0]['User']`
After this the monitor is now running for 12 hours without problems.

I also made a dark theme for the monitor. Maybe you like it also :-)
[myminers.zip](https://github.com/anselal/antminer-monitor/files/1530951/myminers.zip)

**Comment by anselal** [comment]
Thank you for using #AntminerSoftware and for your dark theme, although it is too dark even for my taste.

The code you execute after an exception is the same I am using. Can you paste a screenshot of the debug window when you got the error ? Maybe there are connection errors to your miners.

**Comment by MartinPajak** [comment]
Changed the code back. after only few reloads i get:
`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Martin\Downloads\Mining\antminer-monitor-master\app\views\antminer.py", line 53, in miners
    worker = miner_pools['POOLS'][0]['User']
KeyError: 'POOLS'`

The miners are on local network and i didnt encounter any network problems so far.

**Comment by anselal** [comment]
I don't know what to say @MartinPajak. I checked my code again, tried to reproduced your error but the app works fine. I refresh the page every 2 seconds and no errors occur. The thing is that your workaround makes no sense. You are catching an exception and execute the same code again and it works just fine for you. I really think it is a connection problem. We can connect via `teamviewer` and I can try to debug it to see at least in which machine the error occurs. If it happens all the time on the same machine you should then replace the cable. Send me a pm on twitter so we can talk in private and try to resolve your problem.

**Comment by MartinPajak** [comment]
I never intended this code as a final fix ;-). I only wanted to test/point out, if it will fail again after retry. My tests over 24 hours shows that it never fails. So why should a broken cable never fail in second try? It's not very likely. I think its more like triggering an active state of something (like port of a switch). I just counted/realized that there are four switches/routers on the way to the miners :-)
However you can email me at mpajak@moninet.de, then you can try to debug over teamviewer if you like. I probably can eliminate the router (probably software switch) and one switch from the way and test again.

**Comment by anselal** [comment]
Now that I have an overview of your setup I think I know what caused your error. You see, I have set the timeout for the connection to the cgminer API to `1 second`.

https://github.com/anselal/antminer-monitor/blob/51f7490bde4f2d1b5f37689bf1a2463b512a75b7/app/pycgminer/pycgminer.py#L19

Try to increase it ,say, to 2 seconds and let me know how it went.

**Comment by MartinPajak** [comment]
Outsch, setting the socket timeout to 1s and telling me my cables are broken is very funny ;-)
Usually 60 seconds will be used for socket timeouts. Now with 60s as timeout, the monitor seems to work. I will report, if it should crash again.
However I recommend to use an integrity check for the received data, to make sure the monitor will never crash again on wrong/missed data, bad connection, etc.

**Comment by anselal** [comment]
Actually it is not funny at all. I have feedback from users who have added 30+ miners in the app and it never crashed. Think of it this way. Setting the timeout to 60sec, if there is a connection error on lets say 5 miners, you could wait for the app to load for max 3 minutes. This is unacceptable.

My opinion is that s smaller value for the timeout is decent enough but as it shows it depends on your setup.

**Comment by anselal** [comment]
I should add a socket.timeout exception (https://docs.python.org/2/library/socket.html#socket.timeout)

**Comment by MartinPajak** [comment]
Using the socket.timeout exception and incrementing the timeout value by 1 should work fine, also for internet connections. 
In my network setup even timeout of 3s leads to exceptions. Now with 4s it seems to be stable.

**Comment by MartinPajak** [comment]
Regarding the long waits with high timeouts: you should request the miner status in background only writing the last state to database. In frontend you then only need to display the last state from database, which dont leads to  any waits.

**Comment by anselal** [comment]
I don't wanna do this. That way you don't monitor the miner because you don't get live data.

I am waiting for feedback from a user who has about 100 miners. I am no network expert but if he has no problem with the timeout then you maybe have a lag in your network.

To give you an overview of my setup, my miners are behind a router and a switch which is tens of meters away from router and i don't have any timeout issues

**Comment by anselal** [comment]
@MartinPajak, @merttokgozoglu had the same issue with you and as he stated in #36 that the page refreshes in 10-15 seconds after he set the timeout to 5 seconds. This is caused by his setup because the miners are at different locations.
