### ISSUE TITLE
How can i view 0.0.0.0:5000 from another machine?

### ISSUE THREAD

**Issue by a3igner** [anselal/antminer-monitor#35]
So i got it to run on a linux machine and using lynx i can view the page remotely.
But how can i view the webpage from another machine on the network please?
I have a Mac and want to go to the IP of the linux machine 10.0.0.x:5000 and view that webpage remotely. Thx

**Comment by anselal** [comment]
I think you just answered your question. Just browse the linux machine's ip with port 5000, like e.g. 192.168.1.3:5000

**Comment by a3igner** [comment]
I tried that but it didn’t work. 

I have Apache running already. And other websites I access work fine. 

Does the python script broadcast to outside?

**Comment by anselal** [comment]
0.0.0.0 means accesible from everywhere. Can you check your routes and firewall settings ?

**Comment by a3igner** [comment]
Oh thanks i forgot i had ufw running. how silly!  now it works after enabling port 5000. very good!

THANKS!

**Comment by adstek** [comment]
I just want to add here if you are interested, I installed pagekite on my ubuntu machine to get the page outside my network 😊 adstek.pagekite.me
