### ISSUE TITLE
How do I open the DB through the console?

### ISSUE THREAD

**Issue by sergioclemente** [anselal/antminer-monitor#41]
I tried using sqlite directly and it didn't work. Any pointers?

~/antminer-monitor$ sqlite app/db/app.db
Unable to open database "app/db/app.db": file is encrypted or is not a database

**Comment by gnanet** [comment]
Maybe a too basic question, but which version of **sqlite** you try to use?
Because a search for the error string leads mostly to the suggestion to use **sqlite3** to open sqlite version 3 databases

Is antminer-monitor stopped while you are trying to open the database?

**Comment by sergioclemente** [comment]
yep, you were right.

sudo apt-get install sqlite3
sqlite3 app/db/app.db

did it. Thanks!

**Comment by red0bear** [comment]
i need erase a ip from db ..... could i get some help ?

**Comment by anselal** [comment]
Hey @red0bear,

you can do it via python console but it a bit hard to explain here so the easiest way is to install sqlite3 and edit the database.
With basic sql you can then remove the entry from the `miner` table using:

```sh
# connect to the database
sqlite3 app.db
```

```sh
# list all miners
select * from miner;
```

```sh
# delete the miner with specific id.
# The id is the first column
delete from miner where id=
```

Let me know if that helped !!
