### ISSUE TITLE
Any particular reason why not to make this app generic enough to work with other miner types?

### ISSUE THREAD

**Issue by sergioclemente** [anselal/antminer-monitor#45]
I don't see a reason why this couldn't work with gekkoscience or the avalon miner since its just using the cgminer api. Assuming we build the right adapters for the different device types It should work 

Happy to work on this as well

**Comment by anselal** [comment]
We are currently working on Avalon support. Please check https://twitter.com/AntminerMonitor for updates

**Comment by sergioclemente** [comment]
Glad I asked. I will probably wait to add support to GekkoScience then, so I leverage the framework you built

**Comment by anselal** [comment]
Is the GekkoScience a usb miner ? The software currently only supports network miners. You are welcome to add support for usb miners if you want.

**Comment by anselal** [comment]
We will try to make it generic enough or at least support more miners like Avalon ang GPU rigs. We are working on an API right now as you know 😉
