### ISSUE TITLE
Support for PORT

### ISSUE THREAD

**Issue by hansje69** [anselal/antminer-monitor#47]
Hi there,

 ##I use the same network IP for all my miners, and only have a different port for each miner, if I fill in for example 192.168.1.200:4030, it won't work. I know this is not wrong or anything, but would it be possible to have support for ports as well to solve this quite simple issue?

Thank you

PS. Perhaps not have a separate input field box for field, but simply auto detect all ports on a given IP, or allow people to add :<port> in the IP field. if no port, change nothing, same as now/currently. If mentioned a port, then use that one only :)

**Comment by hansje69** [comment]
def __init__(self, host='localhost', port=4028):
        self.data = {}
        self.host = host
        self.port = port

or perhaps here it's possible to customize it by manually adding in the source code additional ports? Not really user-friendly... but perhaps as a temporary solution?

**Comment by sergioclemente** [comment]
@hansje69 perhaps you should ping @anselal  to review my pull request. There is more stuff there than I've originally sent, but I will be happy to pull back the parts that are not applicable.

**Comment by hansje69** [comment]
I checked your changes, and applied them, but the port function/field doesn't work...

**Comment by anselal** [comment]
This is a duplicate issue #23, #32  and I am closing it.
@hansje69 you are right. The code from @sergioclemente does not work and I will tell you why. It is because he didn't update the call to the CgminerAPI to add the port number.
Since I am closing this issue please don't reply here but at #32

**Comment by sergioclemente** [comment]
My change adds the host port for the http admin interface. It doesn't touch the cgminer entrypoint. Apologies I read your message incorrectly

**Comment by anselal** [comment]
@hansje69 do you forward the RPC port or the Web Interface port?

**Comment by hansje69** [comment]
not sure @anselal , i am not good in knowing the exact words/terms for it, but i think one of them? he changed added a few more than the (i believe its the 4028?) standard ones, by simply adding 4029,4030, and so on..
i hope that helps?

**Comment by anselal** [comment]
@hansje69 port 4028 is the RPC port. The HTTP port is 80, which is the global default for HTTP the protocol. thank you very much, that helped.

**Comment by anselal** [comment]
I close this issue again since we clarified that this is a duplicate :wink:
