### ISSUE TITLE
Adjusting / modifying threshold tempreture warning 

### ISSUE THREAD

**Issue by d3xlim** [anselal/antminer-monitor#53]
Hi Anselal, firstly great work , for this lil app !! love it 

was wondering is there a way i can modify to change the temperature warning msg to a higher number, ? 
at the moment it is set to 80 i want to set to 95 , where about do modify this after i have created the db 

Thanks so much in advance

**Comment by anselal** [comment]
@d3xlim thank you for your kind words. The threshold is hardcoded inside the following file for the time.

https://github.com/anselal/antminer-monitor/blob/0a2b3165b09123f1118f6c007052b0bb5a34f681/app/views/antminer.py#L115

You can change the value anytime even after creating the database

**Comment by d3xlim** [comment]
@anselal got it ! manage to change the threshold limit ! thank you again for guidance and your time for making this, will do my part on the donation 👍  cheers !

**Comment by anselal** [comment]
I am glad I could help. Thank you very much for the donation part, I really appreciate it !!!
