### ISSUE TITLE
Download most updated version

### ISSUE THREAD

**Issue by hansje69** [anselal/antminer-monitor#56]
Where can I download the most updated/recent version? So many things have been changed already, like other miners, port support, and so on. But when I download, it says still 0.2.0 with the same files, perhaps it's me being new on Github, not knowing exactly where to look for the latest zip file, lol.
Cheers.

**Comment by anselal** [comment]
You can download the layest version at https://github.com/anselal/antminer-monitor/archive/master.zip
But the changes you mention haven't benn added yet. The latest version is still 0.2.0

**Comment by hansje69** [comment]
Yes I can see that for myself also, which is why I wonder, why not? And how to get the latest version then? Or are all things mentioned in "Issues" just a place for request, and nothing is done with it? lol

**Comment by anselal** [comment]
The issues are issues and requests. We close them after we deal with them. As long as they are open we are still working on them
