### ISSUE TITLE
Need a programmable script button for each miner rigs

### ISSUE THREAD

**Issue by carlcbilodeau** [anselal/antminer-monitor#63]
**Suggestion:**

I have bought a SainSmart iMatic 16 relay board and controller. This controler has a RJ45 port to connect on my network. There is a 8 and a 16 relay version.
Those 16 relay can be use to shut power to 1 or 2 rigs to reboot them remotly. This is what we call a COLD REBOOT,

On amazon: https://www.amazon.com/SainSmart-iMatic-Controller-Interface-Compatible/dp/B00JJJK2UQ/ref=sr_1_1_a_it?ie=UTF8&qid=1517145595&sr=8-1&keywords=sainsmart+imatic

I have also bought 32 individuals 10pcs 220/240V AC 10A 8PIN Coil Power Relay DPDT LY2NJ HH62P HHC68A-2Z With Socket Base. Those relay are installed in the connection metal box for each rig. So between the SainSmart iMatic 16 relay board and those individuals relay there is only a 12V wire needed.

On aliexpress.com https://www.aliexpress.com/item/Brand-New-10pcs-220-240V-AC-10A-8PIN-Coil-Power-Relay-DPDT-LY2NJ-HH62P-HHC68A-2Z/32789304517.html?spm=a2g0s.9042311.0.0.ViiuoX

On our antminer-monitor we would need just a small button for each rigs so that we can add the necessary code to do a COLD boot each rig. This code should be modifiable by the user. Like in my case, each relay on the iMatic will control two rigs so that I can control 32 rigs with a 16 relay board.

Once this is setup, we can control each of the iMatic relay with very simple commands in any languages.

Here are the various ways to control them.

**From a web browser:**
http://192.168.1.4/30000/00 : Relay-01 OFF
http://192.168.1.4/30000/01 : Relay-01 ON
http://192.168.1.4/30000/02 : Relay-02 OFF
http://192.168.1.4/30000/03 : Relay-02 ON
http://192.168.1.4/30000/04 : Relay-03 OFF
http://192.168.1.4/30000/05 : Relay-03 ON
…
http://192.168.1.4/30000/14 : Relay-16 OFF
http://192.168.1.4/30000/15 : Relay-16 ON
http://192.168.1.4/30000/41 : Enter
http://192.168.1.4/30000/40 : Exit
http://192.168.1.4/30000/42 : Next Page
http://192.168.1.4/30000/43 : Next Page

**ANDROID and IOS**
There is a iMatic app on the playstores.

**Code PHP**
Below is a simple PHP function that will turn a relay on or off, which will hopefully be useful to others.
Here is the code for a 8 relay board. 30000 is the port number on the board that is always at IP address 192.168.1.4.

/**
* sendCommand, sets the state of a specific relay
*
* @param $relay [1-8]
* @param $state [0-1]
*/
function sendCommand($relay,$state) {
$socket = fsockopen('192.168.1.4',30000,$errno,$errstr);
if(!$socket) {
echo $errno . ': ' . $errstr . PHP_EOL;
}
else {
$cmdString = "\xFD\x02\x20" . chr($relay) . chr($state) . "\x5D";
fwrite($socket,$cmdString);
fclose($socket);
}
}

**Batch command line**
https://www.amazon.com/gp/customer-reviews/R3PSQ83T2RM4JQ/ref=cm_cr_arp_d_viewpnt?ie=UTF8&ASIN=B00JJJK2VU#R3PSQ83T2RM4JQ 
Batch script on a Linux server to be able to turn on/off the relays. In bash that is a one liner, for example:

echo -en '\xFD\x02\x20\x01\x01\x5D' | nc -w 1 192.168.1.4 30000
turns on relay 1

HERE ARE SOME OTHER COMMANDS
fd 02 20 f8 88 5d = all on
fd 02 20 f8 08 5d = all off

**ALSO**

try sain():

function sain($ch = -1, $on = -1) {
if ($ch != -1)
sain_send($ch,$on);
$ch = $on = hexdec('ff'); // pide estado, 255
$bin = sain_send($ch,$on);
//info($bin);
return $bin;
}

function sain_send($ch,$on) {
$host = '192.168.1.104';
$port = 30000;
$timeout = 5;
$socket = @fsockopen($host,$port,$errno,$errstr,$timeout);
if (!$socket) {
Â info("Error: " . $errno . ': ' . $errstr . PHP_EOL);
Â return;
}

$cmd = "\xFD\x02\x20" . chr($ch) . chr($on) . "\x5D";
$w = fwrite($socket,$cmd);
$res = fread($socket,20);
//info("ch($ch) on($on) w($w) cmd($cmd) res($res)");
$res = substr($res,1,-1); // quita primer y Ãºltimo
$bin = hexToBin($res);
//info("res($res) bin($bin)");
fclose($socket);
return $bin;
}

function hexToBin($hex) {
$bin = '';

$j = strlen($hex);
for($i=0;$i<$j;$i++)
$bin .= str_pad(decbin(ord($hex[$i])),8,'0',STR_PAD_LEFT);

return $bin;
}

**MOMENTARY PULSE**

To send a momentary pulse, rather then a on and off, looking to just sent a 1 second pulse to a acees control to trigger a door release use a 2200mf Capacitor, and a resistor onto another relay. The resistor bleeds the voltage, you will need 2 of each to toggle as momentary.

**Comment by anselal** [comment]
Sorry, but I don't think this is something an everyday user will use so I am not gonna add this function to the codebase. I am closing this issue. You can always fork my software and add custom functions that suits your needs
