### ISSUE TITLE
Couple of features built into my fork

### ISSUE THREAD

**Issue by sergioclemente** [anselal/antminer-monitor#65]
Let me know if others would find useful and we can discuss how to integrate into @anselal's version:

1) Show fan percentage if provided by the miner
2) Show clock frequency of the miner
3) Restart (By using cgminer api)
4) Verbose section for all messages in the miner
5) Daemon that checks for errors every 5min and sends a mail if something is found
6) Support for Avalon 741
7) Basic authentication that prompts for user/password when getting into the page
![screenshot from 2018-01-31 11 16 07](https://user-images.githubusercontent.com/1606380/35642921-8093a9ec-0679-11e8-88b7-2ddb29e265a5.png)

**Comment by anselal** [comment]
Very nice @sergioclemente thanks.
- To use cgminer-api's restart command did you have to edit the config file of the miner via ssh? I found that this is the only way. I have tested many more commands like changing pool prikrities which is working great !!!
- Did you add support for the Avalon using the snippet i sent you ? I hope it helped.
-  I will add a login screen using the Flask-Login extension
- I would like to see the email daemon code and compare it with my implementation

**Comment by rwalli** [comment]
Hi,

I would also try the "e-mail" feature but the above link give me "Error 404"

Robert

**Comment by sergioclemente** [comment]
I am waiting for @anselal submit the latest changes so i can try merge into his fork, right now the code is already pretty different and a bit incompatible. I've put a gist with the part you are interested

https://gist.github.com/sergioclemente/201bb6f5abffe4c792c897fdf9a69978

**Comment by sergioclemente** [comment]
Closing this for now. Again I am open to migrate features if others find useful
