### ISSUE TITLE
Antminer R4 support

### ISSUE THREAD

**Issue by anselal** [anselal/antminer-monitor#66]
A user on reddit asked for support for Antminer R4.

>https://www.reddit.com/r/BitcoinMining/comments/75twce/antminer_monitor_opensource_monitoring_software/ds1cl3b/
Can you add the R4? It only has 2, instead of 3, boards (126 chips).

**Comment by Artemis3v** [comment]
It was me. Some additional info:
> [ERROR] ASIC chips are missing from miner 'x.x.x.x'. Your Antminer 'S9' has '126/189 chips'.

**Comment by anselal** [comment]
I will include the R4 in the `update_db.py` script probably later today !!!
