### ISSUE TITLE
Error handling null temperature

### ISSUE THREAD

**Issue by mpevner** [anselal/antminer-monitor#69]
In the scenario of a bad miner, it is possible for it to return no temperatures. When this occurs, the max(temps) check fails with the error:
max() arg is an empty sequence

I've done a junky patch to just manually add a 0 entry, but it might be better to detect for this and error accordingly. While I don't think this would cause a crash with the other values, it might be good to check for null scenarios in general, to detect faulty software.

**Comment by anselal** [comment]
Thank yo @mpevner for using my software. I had this error reported by another user but I couldn't debug it to see what exactly caused this error. I think this maybe due to the socket.timeout be set to only 1sec. If you get this error often can you please increase the socket timeout to a higher value, eg. 3, and let me know if this works for you ?

https://github.com/anselal/antminer-monitor/blob/78b600486bb8731bf7c030b4be49cd04de84cb64/app/lib/pycgminer.py#L20

PS: Please update to the latest version because I moved some files around
https://github.com/anselal/antminer-monitor/archive/master.zip

**Comment by mpevner** [comment]
Set that to 5 and undid my quick fix, it seems to work. Oddly, while the miner (a D3) reports no temperatures on its own miner status page, it's still returning A temperature. Of what I'm not entirely sure.

**Comment by anselal** [comment]
Maybe the miner's interface has the same problem with the timeout and cannot retrieve the temperature from cgminer's api. If you think that this fixed your problem please close this issue ;)

**Comment by mpevner** [comment]
Sounds sensible to me! Thanks for the assistance!

**Comment by mpevner** [comment]
Sorry to re-open, but it seems that hardware can fail such that no sane timeout will return a temperature (or even at all). I don't suppose a fault detection for timeouts would be sensible? Interestingly it still returns fan temperatures.

**Comment by anselal** [comment]
Have you checked the miner's interface to see if it shows any temperatures ?

**Comment by mpevner** [comment]
Yes, and no temperatures were shown. As a result, it seems no temperatures are collected (and thus max() null errors)

**Comment by anselal** [comment]
If the miner's web interface doesn't display any temperatures then my software cannot collect any data. Maybe there is an issue with the temperature sensor on the board. I recommend you contact bitmain to resolve your issue.
We would appreciate any feedback.

**Comment by mpevner** [comment]
Quite agreed on replacement -- already working on that. The problem with regards to this though is the page is entirely replaced with a python error -- Ideally it would instead show a 'faulty report' error or somesuch and carry on as normal with the other units.

![empty sequence error](https://user-images.githubusercontent.com/644116/37284906-a4e43540-25d3-11e8-978c-744867f26940.png)

**Comment by anselal** [comment]
@mpevner I guess you are using an older version. I have added a check and fixed this issue. Please upgrade to the latest version and let me know if that fixed your issue so we can close it

**Comment by mpevner** [comment]
Aha! Wonderful!
I was indeed running an older version, I've updated it (and saw the note in the commit history), and it works perfectly.

Thanks!
