### ISSUE TITLE
Reorganize the three pools order

### ISSUE THREAD

**Issue by carlcbilodeau** [anselal/antminer-monitor#70]
Each week or day I have to reorder the three pools of my Antminer. I mine BTC and BCH. I go on https://www.coinwarz.com during the day and if I see BCH pays more than BTC then I switch my pool 1 with my pool 2. 
So I would need a tool that could quickly reorder my three pools order.

Precision: I mine BTC at Slushpool but they don't support BCH so to mine BCH I use Antpool (but they don't pay the tx fees). I don't like BCH but if it gives 0.50$ more per day/S9 then I switch to mine it anyway.

**Comment by anselal** [comment]
I have implemented and tested this feature on my local machine and it works fine. I just need to create the User Interface.

For the time i would suggest to mine in viabtc using the smart pool. This auto switches between BTC and BCH depending on which is more profitable.

**Comment by anselal** [comment]
This is a duplicate issue #46
