### ISSUE TITLE
errors after 20+ ASICs

### ISSUE THREAD

**Issue by shotaatosh** [anselal/antminer-monitor#76]
In last release I'm encouraging errors after adding more than 20 miners, I did try in several farms with D3s and S9s mostly and same. `File "C:\Python27\lib\site-packages\flask\app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\antminer-monitor-master\app\views\antminer.py", line 58, in miners
worker = miner_pools['POOLS'][0]['User']
KeyError: 'POOLS'`
Also I came up to some ideas that would be awesome to have, some of them are already listed here, some of them not.
Login screen - 
Email notifications - also to choose what errors must be notified by email 
Some of my S9s are more than a year old so they have a bunch of damaged chips, it would be great to choose what errors to display/send and what not.
Also I saw an idea of scanning the network option to identify miners, this also can be done just by adding an option to add an IP range, for example 10.98.64.20-59 then tick which models are in this range for example S9s and add.

and lastly thank you for your awesome work, if you will need any kind of ASIC field for testing feel free to contact me

**Comment by anselal** [comment]
I have no overview of your network topology and setup but I assume your miners are behind a couple or more routers and/or switches ?

I have seen the error before. Please try to increase the socket timeout to a higher value like 3 or 5 seconds.

In the latest version (v.0.4.0) the line you have to change is:

https://github.com/anselal/antminer-monitor/blob/c44b6e323b21d6ad879b737bbc2a45e4ffe2dbab/lib/pycgminer.py#L20

**Comment by shotaatosh** [comment]
I will try that and respond
Thanks

**Comment by shotaatosh** [comment]
I guess increasing socket timeout helped this issue,
Thanks!

**Comment by anselal** [comment]
Duplicate at #33
