### ISSUE TITLE
Miner url link

### ISSUE THREAD

**Issue by TRingo1** [anselal/antminer-monitor#78]
Would it be possible to have the url link on the IP address of the miner go right to the ant miner status page? I always am clicking right to the status page.

**currently links** to http://1.1.1.1

would it be possible not sure if each version of miners supported would this work:

**suggested link**  http://1.1.1.1/cgi-bin/minerStatus.cgi

**Comment by anselal** [comment]
Hi there,

thank you for using my software. This is interesting. I am pretty sure all antminers have the same urls for the status page.

It is a very small adjustment but I am currently doing some changes in the code so you will have to wait until the next release ;).

**Comment by TRingo1** [comment]
I do like your software! nice work!
