### ISSUE TITLE
Can I connect remotely ? 

### ISSUE THREAD

**Issue by imac1844** [anselal/antminer-monitor#82]
Can I connect remotely ?

**Comment by hansje69** [comment]
Not yet, I believe it’s part of the different port on the same ip & userlogin “updates”, which is most likely being implemented in the next update. (I hope so)

**Comment by anselal** [comment]
@imac1844 you can connect remotely if you forward a port in you router. If you don't know how you can consult this site https://portforward.com

I close this issue because it is out of topic.

**Comment by imac1844** [comment]
@anselal Thanks for the answer!
 It's not a problem. My Antminers are remote and I have already configured the remote ssh connection (w / RSA key)  and different port then 22 , and w / DynDns service ( I have a dynamic address on the remote router). 
like that :   ( two antminers )
ssh -p 3301 root@myserver.dyndns.info
ssh -p 3302 root@myserver.dyndns.info
and it works!
How do I specify the ports and DynDns url in your script?
Thank!

**Comment by anselal** [comment]
My app runs on port 5000. If you forward that port you gain access to my software but there isn't a login screen yet so be careful not to publish your dyndns to anyone

**Comment by imac1844** [comment]
I have't remote server , only router and miners. I install antminer-monitor on local   MacBook.
As I understand, this option will not work. Thank you for attention !!!

**Comment by anselal** [comment]
I see. The best option is to buy a raspberry pi which will cost you around $50 and install the software there. Most of the users as myself prefer this setup ;)

**Comment by imac1844** [comment]
Yes I have!!!
