### ISSUE TITLE
SSH Power off device

### ISSUE THREAD

**Issue by herveyy** [anselal/antminer-monitor#83]
Firstly I would like to congratulate your efforts on a great application. 

I had a question around the possibility for your application to SSH and power off a device if the high temp alert is activated.

You have shown settings views , but it’s not visible in your latest version , when will this be rolled out please.

Could the worker address be editable to you could have a hyper link , just like the IP goes to the device login, the worker could go to your said wallet to check progress etc.

Many thanks in advance, and apologies if any of the above had previously been requested.

Thanks 

Harvey

**Comment by anselal** [comment]
Dear @herveyy thank you for using my software and for your support !!

SSH Control is duplicate #1 

About the worker address. The worker address is a wallet address only in some cases and it depends on the pool. I could add this functionality to check if the worker is an address and what address it is and create a link. I will open a new issue on this ;)
