### ISSUE TITLE
Support for T9+ 10.5 TH/s

### ISSUE THREAD

**Issue by stangri** [anselal/antminer-monitor#87]
Please add the profile for T9+ 10.5 TH/s variant with 162 chips.

**Comment by stangri** [comment]
https://github.com/anselal/antminer-monitor/pull/88 ;)

**Comment by anselal** [comment]
Yes, but I will add it in the next release ;)

**Comment by anselal** [comment]
Is the hashrate showing up correctly when you add your T9+ as a T9 ?

**Comment by stangri** [comment]
Sorry, can no longer test it, but as far as I remember the only error was incorrect number of chips.

**Comment by Iseman** [comment]
Have checked it with my T9+ and it Shows the correct Hasrate unfortantly in PH/s instead of TH/s.

**Comment by anselal** [comment]
Thank you for the feedback.. I will fix it..
